### ISSUE TITLE
installation location

### ISSUE THREAD

**Issue by zzzgit** [jjpaulo2/pipconf#11]
Why is installed in **/Users/me/Library/Python/3.7/lib/python/site-packages** instead of **/Library/Python/3.7/site-packages**?

On MacOS.

**Comment by jjpaulo2** [comment]
It doesn't look like a this project's issue.

I suggest you to read about pip installations, here:

- https://packaging.python.org/en/latest/tutorials/installing-packages/

Apparently, you had installed for your user (`pip install --user`).
